# Generated by Django 3.0.6 on 2020-05-16 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='image',
        ),
    ]
