# Generated by Django 3.0.6 on 2020-05-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_auto_20200516_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=models.ImageField(blank=True, height_field=700, null=True, upload_to='', width_field=400),
        ),
    ]
