# Generated by Django 3.0.6 on 2020-05-16 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0014_auto_20200516_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='url',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
