# Generated by Django 3.0.6 on 2020-05-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0016_auto_20200516_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='url',
            field=models.TextField(max_length=10000),
        ),
    ]
