# Generated by Django 3.0.6 on 2020-05-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0018_auto_20200516_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='url',
            new_name='image_url',
        ),
    ]
