# Generated by Django 3.0.6 on 2020-05-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0019_auto_20200516_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='image_url',
        ),
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
