# Generated by Django 3.0.6 on 2020-05-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0026_auto_20200516_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='image',
        ),
        migrations.AddField(
            model_name='produto',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
